# Generated by Django 2.2 on 2020-08-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
